version: "3.3"
services:
  back:
    build:
      context: back
    ports:
      - "8000:8000"
    restart: always
    environment:
      SERVER_PORT: 8000
    volumes:
      - ./back:/usr/app/src
  front:
    build:
      context: front
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./front:/usr/app/src
  db:
    image: mariadb:10.4
    ports:
      - "3306:3306"
    restart: always
    environment:
      POSTGRES_USER: admin
      MYSQL_ROOT_PASSWORD: strongpassword
      MYSQL_DATABASE: soul_pet
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mariadb/data
  admin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: "phpmyadmin"
    restart: always
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
    links:
      - db
    depends_on:
      - db
    ports:
      - "8080:80"
volumes:
  db-data: