version: "3.3"
services:
  back:
    container_name: "soul-pet-back"
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    restart: always
    links:
      - db
    depends_on:
      - db
    environment:
      SERVER_PORT: 8000
      TOKEN_LIFETIME_SEC: 600
      DB_HOST: soul-pet-db
      DB_PORT: 3306
      DB_USER: 'user'
      DB_PASSWORD: 'password'
      DB_NAME: 'soul_pet'
      SECRET_KEY: '7CMl4AhyElECTWaUqRjxbl7FsmtYunqf'
      FTP_HOST: soul-pet-sftp
      FTP_PORT: 22
      FTP_USER: nodejs
      FTP_PASSWORD: password
      FTP_PATH_ANIMAL_PICTURES: pictures/animals
      FTP_PATH_EVENT_PICTURES: pictures/events
    volumes:
      - ./back:/usr/app/
      - /usr/app/node_modules
  front:
    container_name: "soul-pet-front"
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    restart: always
    volumes:
      - ./front:/usr/app/
      - /usr/app/node_modules
  db:
    image: mariadb:10.4
    container_name: "soul-pet-db"
    ports:
      - "3307:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: strongpassword
      MYSQL_DATABASE: soul_pet
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mariadb/data
  admin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: "soul-pet-phpmyadmin"
    restart: always
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
    links:
      - db
    depends_on:
      - db
    ports:
      - "8080:80"
  sftp:
    image: atmoz/sftp
    container_name: 'soul-pet-sftp'
    volumes:
      - ./ftp/sftp.d:/etc/sftp.d/
      - sftp-animal-pictures:/home/nodejs/pictures/animals/
      - sftp-event-pictures:/home/nodejs/pictures/events/
    ports:
      - "2222:22"
    command: [nodejs:password:::pictures/animals, nodejs:password:::pictures/events]
volumes:
  db-data:
  sftp-pictures: