version: "3.3"
services:
  back:
    container_name: "soul-pet-back"
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    restart: always
    links:
      - db
    depends_on:
      - db
    environment:
      SERVER_PORT: 8000
      TOKEN_LIFETIME_SEC: 600
      DB_HOST: soul-pet-db
      DB_PORT: 3306
      DB_USER: 'user'
      DB_PASSWORD: 'password'
      DB_NAME: 'soul_pet'
      SECRET_KEY: '7CMl4AhyElECTWaUqRjxbl7FsmtYunqf'
      FTP_HOST: soul-pet-sftp
      FTP_PORT: 22
      FTP_USER: nodejs
      FTP_PASSWORD: password
      FTP_PATH_PICTURES: pictures
      PLACES_API_ID: "OMUJAQFCEKPCCDPHKQW21VUWVJ1YEBGHN0R0RQRQZWJRRNL3"
      PLACES_API_SECRET: "XQ1BKCP2ARAXAQ4M3AQ0P51CJ5DOVLLVYYINOJWXBXQYEVTZ"
    volumes:
      - ./back:/usr/app/
      - /usr/app/node_modules
  front:
    container_name: "soul-pet-front"
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    restart: always
    environment:
      PORT: 3000
      REACT_APP_BACK_URL: "http://localhost:8001/api"
    volumes:
      - ./front:/usr/app/
      - /usr/app/node_modules
  db:
    image: mariadb:10.4
    container_name: "soul-pet-db"
    ports:
      - "3307:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: strongpassword
      MYSQL_DATABASE: soul_pet
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mariadb/data
  admin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: "soul-pet-phpmyadmin"
    restart: always
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
    links:
      - db
    depends_on:
      - db
    ports:
      - "8080:80"
  sftp:
    image: atmoz/sftp
    container_name: 'soul-pet-sftp'
    volumes:
      - ./ftp/sftp.d:/etc/sftp.d/
      - sftp-pictures:/home/nodejs/pictures
    ports:
      - "2222:22"
    command: nodejs:password:::pictures
volumes:
  db-data:
  sftp-pictures: