FROM node:12.2.0-alpine
WORKDIR /usr/app/
ENV PATH /usr/app/node_modules/.bin:$PATH
ENV REACT_APP_BACK_URL https://soul-pet.cs-campus.fr/api
RUN rm package.json || true
RUN rm yarn.lock || true
COPY package.json .
COPY yarn.lock .
RUN yarn install
COPY . .
RUN yarn build
RUN npm install -g serve
CMD ["serve", "-s", "build", "-l", "3000"]