name: Node CI

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  test-front:
    name: Execute tests on the front
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install dependencies
      run: |
        cd front
        yarn install
    - name: Perform tests
      run: |
        cd front
        yarn test --passWithNoTests
